import { User, Campaign, Company, Contact, UserCompanyMatch, DashboardStats, MailboxMessage } from '@/types';

export const mockUser: User = {
  id: '1',
  firstName: 'Francis',
  lastName: 'Gbohunmi',
  email: 'francis@recchx.com',
  role: 'Admin',
  avatar: 'https://ui-avatars.com/api/?name=Francis+Gbohunmi&background=0ea5e9&color=fff',
};

export const mockCampaigns: Campaign[] = [
  {
    id: '1',
    name: 'Q4 Tech Leaders Outreach',
    status: 'Sent',
    scheduledDate: '2025-11-20T09:00:00Z',
    sentCount: 250,
    openCount: 125,
    clickCount: 45,
    replyCount: 18,
    createdAt: '2025-11-15T10:00:00Z',
    updatedAt: '2025-11-24T08:30:00Z',
  },
  {
    id: '2',
    name: 'SaaS Founders Follow-up',
    status: 'Sending',
    scheduledDate: '2025-11-24T14:00:00Z',
    sentCount: 78,
    openCount: 32,
    clickCount: 12,
    replyCount: 5,
    createdAt: '2025-11-22T11:00:00Z',
    updatedAt: '2025-11-24T09:00:00Z',
  },
  {
    id: '3',
    name: 'Healthcare CTO Campaign',
    status: 'Scheduled',
    scheduledDate: '2025-11-26T10:00:00Z',
    sentCount: 0,
    openCount: 0,
    clickCount: 0,
    replyCount: 0,
    createdAt: '2025-11-23T15:00:00Z',
    updatedAt: '2025-11-23T15:00:00Z',
  },
  {
    id: '4',
    name: 'E-commerce Marketing Directors',
    status: 'Draft',
    sentCount: 0,
    openCount: 0,
    clickCount: 0,
    replyCount: 0,
    createdAt: '2025-11-24T08:00:00Z',
    updatedAt: '2025-11-24T08:00:00Z',
  },
  {
    id: '5',
    name: 'Enterprise Sales Leads',
    status: 'Paused',
    scheduledDate: '2025-11-21T08:00:00Z',
    sentCount: 150,
    openCount: 68,
    clickCount: 22,
    replyCount: 9,
    createdAt: '2025-11-18T09:00:00Z',
    updatedAt: '2025-11-22T16:30:00Z',
  },
];

export const mockCompanies: Company[] = [
  {
    id: '1',
    name: 'TechCorp Solutions',
    domain: 'techcorp.com',
    industry: 'Software',
    size: '500-1000',
    location: 'San Francisco, CA',
    contacts: [
      {
        id: '1',
        companyId: '1',
        firstName: 'John',
        lastName: 'Smith',
        email: 'john.smith@techcorp.com',
        role: 'CTO',
        verified: true,
        linkedinUrl: 'https://linkedin.com/in/johnsmith',
      },
      {
        id: '2',
        companyId: '1',
        firstName: 'Sarah',
        lastName: 'Johnson',
        email: 'sarah.j@techcorp.com',
        role: 'VP Engineering',
        verified: true,
      },
    ],
  },
  {
    id: '2',
    name: 'HealthTech Innovations',
    domain: 'healthtech-innov.io',
    industry: 'Healthcare',
    size: '200-500',
    location: 'Boston, MA',
    contacts: [
      {
        id: '3',
        companyId: '2',
        firstName: 'Michael',
        lastName: 'Chen',
        email: 'mchen@healthtech-innov.io',
        role: 'CEO',
        verified: true,
        phoneNumber: '+1-617-555-0123',
      },
      {
        id: '4',
        companyId: '2',
        firstName: 'Emily',
        lastName: 'Rodriguez',
        email: 'emily.r@healthtech-innov.io',
        role: 'Head of Product',
        verified: false,
      },
    ],
  },
  {
    id: '3',
    name: 'FinanceFlow',
    domain: 'financeflow.com',
    industry: 'Fintech',
    size: '100-200',
    location: 'New York, NY',
    contacts: [
      {
        id: '5',
        companyId: '3',
        firstName: 'David',
        lastName: 'Williams',
        email: 'dwilliams@financeflow.com',
        role: 'CTO',
        verified: true,
      },
    ],
  },
  {
    id: '4',
    name: 'EcoRetail Group',
    domain: 'ecoretail.com',
    industry: 'E-commerce',
    size: '1000+',
    location: 'Seattle, WA',
    contacts: [
      {
        id: '6',
        companyId: '4',
        firstName: 'Lisa',
        lastName: 'Anderson',
        email: 'l.anderson@ecoretail.com',
        role: 'Marketing Director',
        verified: true,
      },
      {
        id: '7',
        companyId: '4',
        firstName: 'Robert',
        lastName: 'Taylor',
        email: 'rtaylor@ecoretail.com',
        role: 'VP Sales',
        verified: false,
      },
    ],
  },
  {
    id: '5',
    name: 'CloudScale Systems',
    domain: 'cloudscale.io',
    industry: 'Cloud Services',
    size: '50-100',
    location: 'Austin, TX',
    contacts: [
      {
        id: '8',
        companyId: '5',
        firstName: 'Amanda',
        lastName: 'Martinez',
        email: 'amanda@cloudscale.io',
        role: 'Founder & CEO',
        verified: true,
        linkedinUrl: 'https://linkedin.com/in/amandamartinez',
      },
    ],
  },
];

export const mockUserCompanyMatches: UserCompanyMatch[] = [
  {
    id: '1',
    userId: '1',
    companyId: '1',
    companyName: 'TechCorp Solutions',
    matchedAt: '2025-11-24T07:30:00Z',
    score: 92,
    status: 'New',
  },
  {
    id: '2',
    userId: '1',
    companyId: '2',
    companyName: 'HealthTech Innovations',
    matchedAt: '2025-11-24T06:15:00Z',
    score: 88,
    status: 'Contacted',
  },
  {
    id: '3',
    userId: '1',
    companyId: '3',
    companyName: 'FinanceFlow',
    matchedAt: '2025-11-23T14:20:00Z',
    score: 85,
    status: 'Responded',
  },
  {
    id: '4',
    userId: '1',
    companyId: '4',
    companyName: 'EcoRetail Group',
    matchedAt: '2025-11-23T10:45:00Z',
    score: 79,
    status: 'InProgress',
  },
];

export const mockDashboardStats: DashboardStats = {
  totalSent: 478,
  openRate: 52.3,
  clickRate: 18.7,
  replies: 32,
  activeCampaigns: 2,
  totalProspects: 156,
  unreadMessages: 8,
};

export const mockMailboxMessages: MailboxMessage[] = [
  {
    id: '1',
    from: 'john.smith@techcorp.com',
    subject: 'Re: Partnership Opportunity',
    body: 'Hi, thanks for reaching out. I\'d love to discuss this further. Are you available for a call next week?',
    receivedAt: '2025-11-24T08:30:00Z',
    campaignId: '1',
    contactId: '1',
    isRead: false,
    status: 'Interested',
  },
  {
    id: '2',
    from: 'mchen@healthtech-innov.io',
    subject: 'Re: Healthcare Innovation Summit',
    body: 'This sounds interesting. Can you send me more details about the pricing?',
    receivedAt: '2025-11-24T07:15:00Z',
    campaignId: '3',
    contactId: '3',
    isRead: false,
    status: 'Interested',
  },
  {
    id: '3',
    from: 'dwilliams@financeflow.com',
    subject: 'Re: Fintech Solutions',
    body: 'Not interested at this time, but keep us in mind for future opportunities.',
    receivedAt: '2025-11-23T16:45:00Z',
    campaignId: '1',
    contactId: '5',
    isRead: true,
    status: 'NotInterested',
  },
];
